# Nixpacks configuration for frontend deployment from monorepo root
[phases.setup]
cmds = [
    "corepack enable",
    "corepack prepare pnpm@latest --activate"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pnpm install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "pnpm build:schemas",
    "pnpm build:frontend"
]

[start]
cmd = "cd packages/frontend && exec caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"

[variables]
NODE_ENV = "production"
